server:
  port: 8081
  forward-headers-strategy: framework

# jwt:
#   secret: secret-key-change-this-in-prod-very-long-secret-256bits

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    prometheus:
      enabled: true

app:
  reset-token:
    secret: resetSecretKey12345678901234567890
    expiry-minutes: 30
  audit:
    url: http://audit-service:8086/v1/audit/events
